---
- hosts: testservers
  remote_user: root
  tasks:
        - name: ensure httpd is of latest version 
          yum: name=httpd state=latest
        - name: ensure httpd is running and enable on boot
          service: name=httpd state=started enabled=yes
